<main id="homeGames">
    <table class="tableAdmin">
      <thead>
        <tr>
            <th>Titres des articles</th>
            <th></th>
        </tr>
      </thead>
      <tbody>
      <?php foreach($articles as $article):?>
        <tr>
          <td><?=$article['titleArticles']?></td>
          <td><a class="lienArticle" href="index.php?admin=articleDetails&id=<?=$article['idArticles']?>">Lire</a></td>
        </tr>
      <?php endforeach;?>
      </tbody>
    </table>
</main>
