<main>
  <form class="formAccount" method="post"action="index.php?page=connectAccountSubmit">
    <div class="formDiv">
      <label for="email">Email:</label>
      <input type="email"  name="emailUser" required>
    </div>
    <div class="formDiv">
      <label for="password">Mot de passe:</label>
      <input type="password"  name="passwordUser" required>
    </div>
    <div class="formDiv">
      <button class="buttonFormAccount">Se connecter</button>
    </div>
  </form>
</main>
