<main>
  <form class="formAccount" method="post"action="index.php?page=connectAccountSubmit">
    <div class="formDiv">
      <label for="connectAccountEmail">Email:</label>
      <input id="connectAccountEmail" type="email"  name="emailUser" required>
    </div>
    <div class="formDiv">
      <label for="connectAccountPassword">Mot de passe:</label>
      <input id="connectAccountPassword" type="password"  name="passwordUser" required>
    </div>
    <div class="formDiv">
      <button class="buttonFormAccount">Se connecter</button>
    </div>
  </form>
</main>
