<main>
    <form class="formAccount" method="post"action="index.php?page=createAccountSubmit">
      <div class="formDiv">
        <label for="createAccountPseudo">Pseudo:</label>
        <input id="createAccountPseudo" type="text" name="pseudo" maxlength="15" required>
      </div>
      <div class="formDiv">
        <label for="createAccountEmail">Email:</label>
        <input id="createAccountEmail" type="email"  name="emailUser" required>
      </div>
      <div class="formDiv">
        <label for="createAccountPassword">Mot de passe:</label>
        <input id="createAccountPassword" type="password"  name="passwordUser" required>
      </div>
      <div class="formDiv">
        <label for="lastNameUser">Nom:</label>
        <input id="lastNameUser" type="text"  name="lastNameUser">
      </div>
      <div class="formDiv">
        <label for="firstNameUser">Prénom:</label>
        <input id="firstNameUser" type="text" name="firstNameUser">
      </div>
      <div class="formDiv">
        <button class="buttonFormAccount">Créer</button>
      </div>
    </form>
</main>
