<main>
    <form class="formAccount" method="post"action="index.php?page=createAccountSubmit">
      <div class="formDiv">
        <label for="pseudo">Pseudo:</label>
        <input type="text" name="pseudo" maxlength="15" required>
      </div>
      <div class="formDiv">
        <label for="email">Email:</label>
        <input type="email"  name="emailUser" required>
      </div>
      <div class="formDiv">
        <label for="password">Mot de passe:</label>
        <input type="password"  name="passwordUser" required>
      </div>
      <div class="formDiv">
        <label for="lastNameUser">Nom:</label>
        <input type="text"  name="lastNameUser">
      </div>
      <div class="formDiv">
        <label for="firstNameUser">Prénom:</label>
        <input type="text" name="firstNameUser">
      </div>
      <div class="formDiv">
        <button class="buttonFormAccount">Créer</button>
      </div>
    </form>
</main>
