<main>
  <table class="tableAdmin">
    <thead>
      <tr>
          <th>Titres des articles</th>
          <th>Auteur</th>
          <th>Dates</th>
          <th>Lire L'article</th>
          <th>Mettre en ligne</th>
          <th id="aaa">Supprimer</th>
      </tr>
    </thead>
    <tbody>
    <?php foreach($articles as $article):?>
      <tr>
        <td><?=htmlspecialchars($article['titleArticles'])?></td>
        <td><?=htmlspecialchars($article['auteurArticles'])?></td>
        <td><?=htmlspecialchars($article['dateArticles'])?></td>
        <td><a href="index.php?admin=articleDetails&id=<?=htmlspecialchars($article['idArticles'])?>">V</a></td>
        <td>
          <a href="index.php?admin=articleChecked&id=<?=htmlspecialchars($article['idArticles'])?>&check=<?=htmlspecialchars($article['checkedArticles'])?>"><?=htmlspecialchars($article['checkedArticles'])?></a></td>
        <td><button type="button" id="<?=htmlspecialchars($article['idArticles'])?>" class="deleteArticleButton">X</button></td>
      </tr>
    <?php endforeach;?>
    </tbody>
  </table>
  <table class="tableAdmin">
    <thead>
      <tr>
          <th>Pseudo</th>
          <th>Email</th>
          <th>Nom</th>
          <th>Prénom</th>
      </tr>
    </thead>
    <tbody>
    <?php foreach($users as $user):?>
      <tr>
        <td><?=htmlspecialchars($user['pseudo'])?></td>
        <td><?=htmlspecialchars($user['emailUser'])?></td>
        <td><?=htmlspecialchars($user['lastNameUser'])?></td>
        <td><?=htmlspecialchars($user['firstNameUser'])?></td>
      </tr>
    <?php endforeach;?>
    </tbody>
  </table>
</main>
