<main>
  <table class="tableAdmin">
    <thead>
      <tr>
          <th>Titres des articles</th>
          <th>Auteur</th>
          <th>Dates</th>
          <th>Lire L'article</th>
          <th>Mettre en ligne</th>
          <th id="aaa">Supprimer</th>
      </tr>
    </thead>
    <tbody>
    <?php foreach($articles as $article):?>
      <tr>
        <td><?=$article['titleArticles']?></td>
        <td><?=$article['auteurArticles']?></td>
        <td><?=$article['dateArticles']?></td>
        <td><a href="index.php?admin=articleDetails&id=<?=$article['idArticles']?>">V</a></td>
        <td><a href="index.php?admin=articleChecked&id=<?=$article['idArticles']?>&check=<?=$article['checkedArticles']?>"><?=$article['checkedArticles']?></a></td>
        <td><button type="button" id="<?=$article['idArticles']?>" class="deleteArticleButton">X</button></td>
      </tr>
    <?php endforeach;?>
    </tbody>
  </table>
  <table class="tableAdmin">
    <thead>
      <tr>
          <th>Pseudo</th>
          <th>Email</th>
          <th>Nom</th>
          <th>Prénom</th>
      </tr>
    </thead>
    <tbody>
    <?php foreach($users as $user):?>
      <tr>
        <td><?=$user['pseudo']?></td>
        <td><?=$user['emailUser']?></td>
        <td><?=$user['lastNameUser']?></td>
        <td><?=$user['firstNameUser']?></td>
      </tr>
    <?php endforeach;?>
    </tbody>
  </table>
</main>
