<!DOCTYPE html>
<html lang="fr" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css">
    <script
      src="https://code.jquery.com/jquery-3.4.1.min.js"
      integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
      crossorigin="anonymous"></script>
    <link rel="stylesheet" href="www/css/normalize.css">
    <link rel="stylesheet" href="www/css/style.css">
    <title>MIVA- <?=$template?></title>
  </head>
    <body>
      <header>
        <nav id=navHeader>
          <ul>
            <?php if(!isset($_SESSION["user"])):?>
              <li><a href="index.php">MIVA</a></li>
            <?php endif;?>
            <?php if(isset($_SESSION["user"])):?>
              <li><a href="index.php">Articles</a></li>
              <li><a href="index.php?page=yourAccount"><i class="fas fa-user"></i></a></li>
              <li><a href="index.php?page=disconnectAccount"><i class="fas fa-user-times"></i></a></li>
              <li><a href="index.php?page=createArticle"><i class="fas fa-feather-alt"></i></a></li>
            <?php endif;?>
          </ul>
        </nav>
      </header>
         <?php include ($template.".phtml");?>
        <footer>
        </footer>
        <script src="www/js/event.js"></script>
        <script src="www/js/main.js"></script>
        <script src="www/js/ajax.js"></script>
    </body>
</html>
